FROM debian
RUN sed 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' -ri.bak /etc/apt/sources.list.d/debian.sources
RUN apt update
RUN apt upgrade -y
RUN apt install build-essential -y
RUN apt install vim -y
RUN apt install tmux -y
RUN apt install git -y
RUN apt install curl -y
RUN apt install wget -y
RUN apt install cmake -y
RUN apt install gdb -y
RUN apt install zsh -y
RUN apt install fzf -y
